### ISSUE TITLE
About Training on CUDA devices

### ISSUE THREAD

**Issue by WMF1997** [FighterLYL/GraphNeuralNetwork#1]
Hello @FighterLYL 
Thank you for sharing the code of the book!
In chapter 5's Jupyter Notebook, I found a small problem in its cell 9. 

For those who use CUDA device to run this cell. 
```python
def test(mask):
    model.eval()
    with torch.no_grad():
        logits = model(tensor_adjacency, tensor_x)
        test_mask_logits = logits[mask]
        predict_y = test_mask_logits.max(1)[1]
        accuarcy = torch.eq(predict_y, tensor_y[mask]).float().mean()
    return accuarcy, test_mask_logits.numpy(), tensor_y[mask].numpy()
```
This is your original code. And I run it on a CUDA device, then it returns such error. 
```
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
It shows that the tensor is still in CUDA device. and use ```.cpu()``` method can solve this. 

So, I modified the code:
```python
def test(mask):
    model.eval()
    with torch.no_grad():
        logits = model(tensor_adjacency, tensor_x)
        test_mask_logits = logits[mask]
        predict_y = test_mask_logits.max(1)[1]
        accuarcy = torch.eq(predict_y, tensor_y[mask]).float().mean()
    # return accuarcy, test_mask_logits.numpy(), tensor_y[mask].numpy()

    # NOTE(WMF): if you want to use CUDA device, and... do not detach them?
    if device == 'cpu':
        return accuarcy, test_mask_logits.detach().numpy(), tensor_y[mask].detach().numpy()
    else:
        return accuarcy, test_mask_logits.detach().cpu().numpy(), tensor_y[mask].detach().cpu().numpy()
```
I added a ```.detach()``` to make sure the result is detached from PyTorch's computation map. (I tried the code without ```.detach()```, it still works, so ```.detach()``` can be an optional. 

yours sincerely, 
@wmf1997

**Comment by FighterLYL** [comment]
Yeah, this is bug, thanks for point it out. You can fix it by adding `.cpu().numpy()` . There is no need to use function `detach()` and condition `device == 'cpu'`.
