### ISSUE TITLE
关于chapter5代码运行发生错误

### ISSUE THREAD

**Issue by jkwang93** [FighterLYL/GraphNeuralNetwork#14]
跑了一下里面的jupyter文件，报错RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target'，自己将target改成long类型也会报错RuntimeError: multi-target not supported at C:/w/1/s/tmp_conda_3.6_045031/conda/conda-bld/pytorch_1565412750030/work/aten/src\THCUNN/generic/ClassNLLCriterion.cu:15

**Comment by FighterLYL** [comment]
我这边运行notebook是没有问题的，你是不是把target转换为了one-hot形式，可以把target打印出来看一下。

**Comment by jkwang93** [comment]
> 我这边运行notebook是没有问题的，你是不是把target转换为了one-hot形式，可以把target打印出来看一下。

对的，非常感谢
