### ISSUE TITLE
Core数据集无法下载

### ISSUE THREAD

**Issue by xiaolizai** [FighterLYL/GraphNeuralNetwork#17]
你好，Chapter5中Cora数据集的下载链接https://raw.githubusercontent.com/kimiyoung/planetoid/master/data打不开，请问有其他方式下载该数据集吗？

**Comment by wight911** [comment]
同问。数据下载链接失效了。

**Comment by FighterLYL** [comment]
我在仓库里增加了原始的[Cora数据](https://github.com/FighterLYL/GraphNeuralNetwork/tree/master/data/cora)，你们可以直接clone下来，将数据文件放在`chapter5/cora/raw`或者`chapter7/cora/raw` 下面

**Comment by wight911** [comment]
好的，谢谢！


原始邮件
发件人:FighterLYLnotifications@github.com
收件人:FighterLYL/GraphNeuralNetworkGraphNeuralNetwork@noreply.github.com
抄送:wight911837950604@qq.com; Commentcomment@noreply.github.com
发送时间:2020年2月17日(周一) 21:26
主题:Re: [FighterLYL/GraphNeuralNetwork] Core数据集无法下载 (#17)


我在仓库里增加了原始的Cora数据，你们可以直接clone下来，将数据文件放在chapter5/cora/raw或者chapter7/cora/raw 下面

**Comment by xiaolizai** [comment]
太感谢了

**Comment by wl15321115635** [comment]
cora数据的下载URL 现在不可用，其他地方下载到的第五章代码运行中UnpicklingError: invalid load key, '\x0a'错误，请问什么原因呢？有新的数据集链接吗？

**Comment by FighterLYL** [comment]
@wl15321115635 有使用仓库提供的数据集吗, 具体参考仓库README中FAQ部分

**Comment by wl15321115635** [comment]
使用了仓库的数据集，cora数据集保存到本地，放到预定目录，运行第五章代码—加载数据部分（第7段），仍然出现UnpicklingError: invalid load key, '\x0a'错误
