### ISSUE TITLE
第五章代码的一个问题

### ISSUE THREAD

**Issue by Riofd** [FighterLYL/GraphNeuralNetwork#19]
作者你好，我想问一下如果我想在第五章代码的基础上改一下，在新的数据集上测试，但是我的输入数据维度是3D的，这个时候会遇到输入特征维度出错，因为Cora数据集输入特征维度就是int类型的，这种情况应该怎么改呢

**Comment by FighterLYL** [comment]
输入数据三维是由于每个节点的特征都是二维的么，如果是这样你可以尝试在进行邻居聚合时将节点特征转换为一维；另一种方式是看是否可以使用Tensor的稀疏矩阵乘法

**Comment by Tina-YTT** [comment]
第五章代码跑的时候出现问题TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.请问如何解决

**Comment by FighterLYL** [comment]
> 第五章代码跑的时候出现问题TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.请问如何解决

可能是因为你的pytorch版本过低，请升级到更新的版本
