### ISSUE TITLE
P133页GraphSAGE的伪代码第9行

### ISSUE THREAD

**Issue by lcxq** [FighterLYL/GraphNeuralNetwork#21]
一、
P133页GraphSAGE的伪代码第9行应该是for k = 1...K do 吧，这个循环不应该从src_node作聚合了，而是从远处的node聚合，原论文也是写的for k = 1...K do
二、
不是很理解p152页GraphSAGE代码实现的forward部分，为什么有两个分别遍历num_layers和num_layers - 1的for循环，我理解的算法似乎做一次从1到K的聚合遍历就行了，希望能解释一下

**Comment by FighterLYL** [comment]
1. 对于问题1：确实k应该从1..K
2. 对于问题2：代码的实现与伪代码不完全一致，伪代码中只有一次遍历是因为 B^k 中存放的是中心节点及其(K - k) 阶的所有采样的节点，而在代码实现中存储的采样结果是 `[中心节点；中心节点的1阶采样；1阶结果的采样，即2阶]`，因此需要两个遍历num_layers （对应于K）和 (num_layers - $\ell$)
