### ISSUE TITLE
The download url for Cora data is unavailable now!

### ISSUE THREAD

**Issue by jxshang** [FighterLYL/GraphNeuralNetwork#23]
The download url for Cora data (chapter 5), i.e., https://raw.githubusercontent.com/kimiyoung/planetoid/master/data, is unavailable now. When I try this url, it leads me to the 404 not found page.

**Comment by FighterLYL** [comment]
please check issue #17

**Comment by jxshang** [comment]
Thx for the rapid reply. The problem has been solved.
