### ISSUE TITLE
第八章程序运行出错

### ISSUE THREAD

**Issue by loovi7** [FighterLYL/GraphNeuralNetwork#26]
E:\深度学习开源项目\GraphNeuralNetwork-master\chapter8>python self_attn_pool.py
Traceback (most recent call last):
  File "self_attn_pool.py", line 11, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'

但是我已经安装过sklearn了，请问该如何解决？
另外该程序用cpu可以跑的吧？
谢谢！

**Comment by FighterLYL** [comment]
1. 你可以重新安装下`python -m pip install -U scikit-learn`，然后确认下是否安装成功`python -c "import sklearn; sklearn.show_versions()"`
2. 可以使用CPU运行的

**Comment by loovi7** [comment]
> 1. 你可以重新安装下`python -m pip install -U scikit-learn`，然后确认下是否安装成功`python -c "import sklearn; sklearn.show_versions()"`
> 2. 可以使用CPU运行的

作者您好！之前的问题解决了，不过出现了新的问题：
No module named 'torch_scatter'
按照readme中的解释执行pip install --verbose --no-cache-dir torch-scatter安装失败，命令行刷了好多内容，最后是：
ModuleNotFoundError: No module named 'torch_scatter'
不知如何解决，环境win10 python3.7.5 torch1.2.0 cpu

**Comment by FighterLYL** [comment]
你看下pip install --verbose --no-cache-dir torch-scatter 输出内容中是因为什么原因没有安装成功

**Comment by loovi7** [comment]
> 你看下pip install --verbose --no-cache-dir torch-scatter 输出内容中是因为什么原因没有安装成功

前面在镜像源中找到torch_scatter后，接下来
Running setup.py (path:C:\Users\lww\AppData\Local\Temp\pip-install-svoxoocm\torch-scatter\setup.py) egg_info for package torch-scatter
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lww\AppData\Local\Temp\pip-install-svoxoocm\torch-scatter\setup.py", line 6, in <module>
        **import torch
    ModuleNotFoundError: No module named 'torch'**
Cleaning up...
  Removing source in C:\Users\lww\AppData\Local\Temp\pip-install-svoxoocm\torch-scatter
Removed torch-scatter from https://mirrors.aliyun.com/pypi/packages/98/a9/47cd92673b6ba251240d587815c763baac2099b07bb76fecdb3b7ae5cece/torch_scatter-2.0.4.tar.gz#sha256=db6c9eca919b86f3eb6102dd0e1215af72e39ed3a4e8d142e6a21d3f20d5c244 from build tracker 'C:\\Users\\lww\\AppData\\Local\\Temp\\pip-req-tracker-0bjteymk'
Removed build tracker 'C:\\Users\\lww\\AppData\\Local\\Temp\\pip-req-tracker-0bjteymk'
**ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**

其中提到了no module named 'torch',是否说torch版本不对？

**Comment by FighterLYL** [comment]
没有找到torch，估计是你电脑上有多套的python环境，你使用的pip与python不一致，换成`python -m pip install --verbose --no-cache-dir torch-scatter`

**Comment by loovi7** [comment]
> 没有找到torch，估计是你电脑上有多套的python环境，你使用的pip与python不一致，换成`python -m pip install --verbose --no-cache-dir torch-scatter`
还是有问题
![(UY {L_`NU_}}C06%G$PJ@M](https://user-images.githubusercontent.com/42432519/77432991-c2396300-6e19-11ea-99b8-1d2f47a86580.png)
为什么会提到cuda啥的

**Comment by FighterLYL** [comment]
torch_scatter 安装的时候会默认去找cuda的路径，你可以通过设置环境变量`FORCE_CPU=1`来屏蔽该行为，参考https://github.com/rusty1s/pytorch_scatter/blob/master/setup.py#L13。

你可以试试这个命令是否可行：`FORCE_CPU=1 python -m pip install --verbose --no-cache-dir torch-scatter`，我不确定windows上这样设置是否有效
