### ISSUE TITLE
关于图卷积神经网络

### ISSUE THREAD

**Issue by GeniusYx** [FighterLYL/GraphNeuralNetwork#28]
作者您好，你在解释最初如何设计图卷积神经网络的过程中，你提到可以对频率响应矩阵进行参数化，之后解释他的不足的原因解释为：

“引入的学习参数过多,需要学习的参数量与图中的节点数一致,这在大规模图数据,比如上亿节点数规模
的图中,极易发生过拟合问题。”

可是按照我的理解，在现在GCN的设计中，参数量应该是大于节点个数的吧？所以我不是很懂这个部分的理解。另外，我不知道这句话是不是有个前提，那就是参数量大这个情况只会发生在大规模图数据。

**Comment by FighterLYL** [comment]
在一些面向实际场景的图中，使用GCN时其参数量不会特别大，堆叠的层数不会过多（≤5），主要的原因在于这些图中所包含的结构信息和节点属性信息是相对high-level的，并不像CNN一般输入是像素这种low-level的表示。参数量与图数据的规模不存在正相关的关系，参数量主要取决于要解决的问题和数据的情况。
