### ISSUE TITLE
关于建图关系矩阵疑问

### ISSUE THREAD

**Issue by dfgan** [FighterLYL/GraphNeuralNetwork#29]
https://github.com/FighterLYL/GraphNeuralNetwork/blob/7bad93377f7f6047e1c9269652a36b33ea64c3c9/chapter5/GCN_Cora.py#L131

**Comment by dfgan** [comment]
这里我的理解是论文引用应该是有向图，但是这里矩阵的创建方式感觉像无向图，请作者解答一下，谢谢。

**Comment by FighterLYL** [comment]
当用这个图表示明确的引用关系时，确实应该是有向图。对于GCN来说，本质上是一个聚合邻居的过程，将有向图转换为无向图可以让图中每个节点都能够从邻居聚合信息，否则信息的传播只能沿着有向边进行。一般的场景下，我们都会忽略掉边方向的信息。
