### ISSUE TITLE
数据加载

### ISSUE THREAD

**Issue by Jerry992** [FighterLYL/GraphNeuralNetwork#3]
数据加载是否要VPN，5章程序训练不了代码显示[WinError 10054] 远程主机强迫关闭了一个现有的连接。>，打开数据集连接显示404

**Comment by xiaolun0** [comment]
add data files to chapter5/cora/raw/
#from "https://github.com/kimiyoung/planetoid/tree/master/data"

**Comment by FighterLYL** [comment]
As @xiaolun0 said, you can manually download cora related data which start with `ind.cora` from [here](https://github.com/kimiyoung/planetoid/tree/master/data) then place them to path `chapter5/cora/raw`
