### ISSUE TITLE
关于在R8数据集上使用GraphSAGE的问题

### ISSUE THREAD

**Issue by Y0ungMay** [FighterLYL/GraphNeuralNetwork#30]
你好，我尝试在R8数据集上使用GraphSAGE进行分类预测
由于你实验用的.x,.y,.alllx一类的文件都是直接下载的，所以我用了别人的代码来处理数据并生成这一类文件。但在实验中遇到了loss一直为NAN的原因。网上说可能是输入数据有问题，但是我比较之后，发现两者似乎没有明显差别，现在就有点懵。不知道你有没有在别的数据集上用过GraphSAGE？
另外，请问你知道哪里可以下到R8，MR，20ng这一类数据集的.x,.y,.allx这一类文件吗？

**Comment by FighterLYL** [comment]
1. 关于Loss为Nan可能的原因有多种，建议你从输入开始核查，包括原始数据中是否存在异常数据，比如有值异常大，数据归一化是否会导致NaN的出现；如果输入没有问题，就对模型逐层核查，看是在什么地方出现的NaN，进而反推为NaN的原因。如果训练一开始Loss就为NaN，大概率是模型输入有问题
2. 数据上，可能每种数据集格式不太一样，可以自行进行处理得到模型的输入

**Comment by Y0ungMay** [comment]
你好，我输出了一下数据，发现sampling_x的第一位数据就出现了nan，然后再查看x，发现归一化之前，我的x.sum只有22点几，是不是x这里出现了问题啊？

**Comment by FighterLYL** [comment]
那就是归一化这里有0或者很小的数，导致产生了无穷大的值，你可以将inf的值全部设置为0

**Comment by Y0ungMay** [comment]
请问inf是什么啊？代码里好像没看见这个变量

**Comment by FighterLYL** [comment]
归一化之后输入的x可能有np.inf，表示无穷大，你需要将这种值设置为0，比如这样 `x[x == np.inf] = 0`

**Comment by Y0ungMay** [comment]
好的，谢谢，我去试试看
