### ISSUE TITLE
关于固定滤波器的性质

### ISSUE THREAD

**Issue by ryanbbd** [FighterLYL/GraphNeuralNetwork#32]
首先感谢作者写了这本书，作为入门书我觉得很不错。由于理解还不够，想问作者几个问题：
1. P99页hat(L_sym)看起来不像是I+L，也就是hat(L)的直接正则化，我理解的正则化是对I+L的对角线归一化，如果按照我的理解的话，这个hat(L_sym)应该不是，希望作者帮忙解惑一下。
2. P125页 v1=hat(D)^(1/2)I 怎么会处处相等，hat(D) = D+I只是对角矩阵，其对角元和图的节点度相关，如何理解处处相等？

**Comment by FighterLYL** [comment]
1. hat(L_sym)是hat(A)的对称归一化，由于这里的A是扩增的形式，因此D也应该对应取扩增的形式hat(D)，书中给出了hat(L_sym)的形式，你体会一下。
2. p125页这里的处处相等的确说的不够准确，应该这样来说，经过拉普拉斯算子的极限滤波之后，图信号x就变成了在第一特征向量上的投影向量，见式(6.6)，因此有两个层面的过平滑问题，第一个，对于不同的图信号x而言，输出的投影向量仅仅是模的不同，方向是一致的，这引发了对整个图信号的分类问题，第二个，对于单一的图信号，即在单个图节点层面看，最后所有节点上的图信号都取得了固定的数值，与各自的度相关，这样就消去了本身图信号的差异，分类也是很困难的。
