### ISSUE TITLE
【图分类】代码中，将数据集换成另外的二分类数据集比如：DBLP_v1，提示：类值为负！

### ISSUE THREAD

**Issue by VeronicaWang** [FighterLYL/GraphNeuralNetwork#38]
在第八章中，用其他数据集进行训练，比如DBLP_v1,运行结果提示：类值不能为负值。具体错误提示如下：
![image](https://user-images.githubusercontent.com/27531170/85113922-a8f25800-b24a-11ea-8436-c8602e4a5ce9.png)

提示在ont_hot()函数中出现了问题。请问这个问题如何解决呢？该模型是否具有通用性？对数据集有什么要求吗？

**Comment by FighterLYL** [comment]
问题应该是node_labels里面含有负数，你检查下node_labels的值

**Comment by VeronicaWang** [comment]
> 
> 
> 问题应该是node_labels里面含有负数，你检查下node_labels的值

谢谢你的回答。但是node_labels里面是没有负数的。我已经检查过了。
![图片](https://user-images.githubusercontent.com/27531170/85134949-d7365e80-b26f-11ea-91d5-1884f428f2d0.png)

**Comment by FighterLYL** [comment]
你应该检查传入onehot函数的node_labels的合法性, 在程序中打印下node_labels的最小值。
