### ISSUE TITLE
关于chapter7 graphsage  每轮epoch最后一轮batch src_node变成1000 但是设置的根节点数目为16

### ISSUE THREAD

**Issue by shanhaoran** [FighterLYL/GraphNeuralNetwork#39]
![图1](https://user-images.githubusercontent.com/56160442/85389059-84172100-b579-11ea-8393-3e05f0dbf86c.png)
![图2](https://user-images.githubusercontent.com/56160442/85389065-86797b00-b579-11ea-9b9c-87a9ef750411.png)
![图3](https://user-images.githubusercontent.com/56160442/85389082-8aa59880-b579-11ea-857c-b85484b1414f.png)
如图1，eopch000 batch019的时候， 打印图2samping函数中的src_noded,  src_node的个数变成了1000，但是在图3中在main的train函数中打印batch_src_index 输出结果为0
每个epoch的最后一个batch都有这个问题， batch_src_node的个数不是设置的16吗？为什么在最后一个batch  batch_src_node的个数会变成0，而且传入到multihop_sampling中src_node的个数变成了1000？

**Comment by FighterLYL** [comment]
训练的时候是每个epoch结束之后在验证集上进行测试, [代码在这](https://github.com/FighterLYL/GraphNeuralNetwork/blob/master/chapter7/main.py#L55) ，你打印的1000对应于验证集的源节点数。

**Comment by shanhaoran** [comment]
但是每个epoch不是有20个batch吗，0-19，为什么在最后一个batch的时候直接跳过了，在最后一次batch中无论打印什么都打印不出来，直接进行验证了啊，不是应该先进行for循环中的20个batch再运行验证吗？
