### ISSUE TITLE
73页，公式4-10和4-11

### ISSUE THREAD

**Issue by dream-in-night** [FighterLYL/GraphNeuralNetwork#4]
4-10与4-11都是算KL距离，一个是单竖线，一个是双竖线，请问这两个有什么区别吗？上下文中没有说明，百度和CSDN里都是用的双竖线，这里不明白，请教一下，谢谢

**Comment by FighterLYL** [comment]
不好意思给你造成了困扰，这里确实是编辑错误，都应该是双竖线
