### ISSUE TITLE
关于书的92、93、94页的疑问和错误。

### ISSUE THREAD

**Issue by haowuliao** [FighterLYL/GraphNeuralNetwork#40]
92页：5.21公式里面的h0, h1这些系数，则么计算？
93页：5.23公式里面的hk 的k应该是下标而不是上标。
94页：x(1) = Hx，x(2)=Hx(1)， 根据93页的公式，不对吧。应该是x(1)=Lx， x(2)=Lx(1)。而且在已知H=A的情况，系数向量h则么计算得到。根据5.21公式，先算出L，把书上的系数向量h代入公式，计算得到H  和书上写的 H 不一致。

**Comment by FighterLYL** [comment]
问题1：系数计算参考公式5.27
问题2：这是个笔误，感谢指正
问题3：参看仓库中的勘误文件，有更正一些图滤波器的说法。公式推导使用的图位移矩阵为L，举例计算采用的图位移矩阵为S。书中没有区分图位移矩阵和图滤波器，造成了一些歧义，抱歉。
