### ISSUE TITLE
能不能把电子版本里面的错误都改掉？

### ISSUE THREAD

**Issue by erichuazhou** [FighterLYL/GraphNeuralNetwork#41]
买了亚马逊kindle版本的电子书，感觉是第一版的，能不能把勘误的错误在电子书中改正。不然得边看电子书边看勘误pdf。谢谢

**Comment by FighterLYL** [comment]
感谢建议，我与出版社联系了，他们会尽快更正。

**Comment by FighterLYL** [comment]
出版社确认了下他们已经于6.22更新了，你更新下电子书试一下

**Comment by erichuazhou** [comment]
我今天再次确认，amazn的kindle电子书版本，并没有修改任何错误。错误还是一大堆。

**Comment by erichuazhou** [comment]
@FighterLYL

**Comment by FighterLYL** [comment]
> 我今天再次确认，amazn的kindle电子书版本，并没有修改任何错误。错误还是一大堆。

你例举几处没有修改的地方，我去核实一下 @erichuazhou

**Comment by erichuazhou** [comment]
所有出现在勘误.pdf上的都没有修改。比如公式(2.5)。
![image](https://user-images.githubusercontent.com/44012390/87113607-3b61a680-c2a1-11ea-8759-d72c4f9009e4.png)

**Comment by FighterLYL** [comment]
你有尝试更新下电子书吗，你看的版本应该是旧的

**Comment by erichuazhou** [comment]
删除重新下载了很多遍

**Comment by erichuazhou** [comment]
我删除了kindle pc，重新安装，注册，再重新下载，还是老版本。但我看网站上的"在线试读"是新版本。是不是amazon展示的是新版本，但用户用kindle pc下载的还是老版本？ 请向amazon反馈下，谢谢。

**Comment by FighterLYL** [comment]
需要从亚马逊官网登录，通过 `我的账户`-> `管理我的内容和设备`，就可以看到电子书有更新的提示，进行更新就行了。参考下这个链接 [update kindle books](https://www.howtogeek.com/tips/how-to-get-the-latest-version-of-your-kindle-books-including-ours/)。

**Comment by erichuazhou** [comment]
我确认， 我的账户-> 管理我的内容和设备，无电子书更新提示。

**Comment by erichuazhou** [comment]
@FighterLYL

**Comment by FighterLYL** [comment]
反馈给出版社了， 他们还在排查问题

**Comment by FighterLYL** [comment]
出版社建议你给亚马逊客服邮件反馈解决 @erichuazhou

**Comment by FighterLYL** [comment]
@erichuazhou 问题解决了吗
