### ISSUE TITLE
5.5卷积神经网络的疑问？

### ISSUE THREAD

**Issue by erichuazhou** [FighterLYL/GraphNeuralNetwork#42]
书中：
![image](https://user-images.githubusercontent.com/44012390/87868699-4ddb8e80-c9cb-11ea-8221-563b27daa2ed.png)
如何证明是图位移算子？？这应该和x1自身有关系吧，不一定是图移位算子。
@FighterLYL

**Comment by FighterLYL** [comment]
你理解的对，确实是跟图信号本身有关系
