### ISSUE TITLE
something seems wrong in the file of main.py in chapter07

### ISSUE THREAD

**Issue by zhaoyin214** [FighterLYL/GraphNeuralNetwork#45]
something seems wrong in the file of main.py in chapter07

```
# line 31 - 32
train_index = np.where(data.train_mask)[0]
train_label = data.y[train_index]
```

```
# line 45 - 46
batch_src_index = np.random.choice(train_index, size=(BTACH_SIZE,))
batch_src_label = torch.from_numpy(train_label[batch_src_index]).long().to(DEVICE)
```

here, `train_label` should be `data.y` but not `data.y[train_index]`

**Comment by FighterLYL** [comment]
Yeah, that's a bug, it maybe change the sample's label, thanks.

**Comment by WisleyWang** [comment]
这里是不是有个错误，不是很明白，在net.py中
`    def forward(self, node_features_list):
        hidden = node_features_list
        for l in range(self.num_layers):
            next_hidden = []
            gcn = self.gcn[l]
            for hop in range(self.num_layers - l):
                src_node_features = hidden[hop]
                src_node_num = len(src_node_features)
                neighbor_node_features = hidden[hop + 1] \
                    .view((src_node_num, self.num_neighbors_list[hop], -1))
                h = gcn(src_node_features, neighbor_node_features)
                next_hidden.append(h)
            hidden = next_hidden`
原代码的self.num_layers==len(num_neighbors_list)==2,而len(node_features_list)==3
开始时，hidden=node_features_list,所以len(hidden)==3
第一层循环执行两次，第二层循环执行一次。
在外循环第一次执行后,hidden=next_hidden,得到的len(hidden)==1
此时第二次循环时，执行到neighbor_node_features = hidden[hop + 1],会出现越界。
