### ISSUE TITLE
第九章的代码

### ISSUE THREAD

**Issue by 949980626** [FighterLYL/GraphNeuralNetwork#47]
您好  我想问一下为什么第九章的代码最后我得到的结果特别低啊 LOSS1.26  RSME0.92

**Comment by FighterLYL** [comment]
代码中的超参数没有仔细调整, 另外代码实现的某些细节与原作实现有区别(比如原作在输入上加了dropout)

**Comment by 949980626** [comment]
好的  谢谢  麻烦您了
