### ISSUE TITLE
关于第7章GAT部分的一些错误

### ISSUE THREAD

**Issue by DennisShaw** [FighterLYL/GraphNeuralNetwork#48]
P137页 图7-4softmax输出的节点应为α<sub>ij</sub>而非e<sub>ij</sub>
P138页 公式7.8 α<sub>ij</sub>的计算公式，分母中的Wh<sub>j</sub>，应为Wh<sub>k</sub>，与前面的求和函数的第k个节点应保持一致

**Comment by FighterLYL** [comment]
感谢指正
