### ISSUE TITLE
第五页K阶子图定义

### ISSUE THREAD

**Issue by alice-cool** [FighterLYL/GraphNeuralNetwork#49]
作者您好，我感觉第五页K阶子图定义有些问题。这里面写的E‘={eij|任意 vj,d(vi,vj)<=k}
这里面如果eij图中根本不存在这条边，但是存在这个路径所以说这可能会有些问题。所以我认为E‘={elm|任意 vj,d(vi,vj)<=k，elm属于Pij}
希望得到您的回复。目前正在认真阅读图卷积知识。

**Comment by alice-cool** [comment]
第8页，如果同构图是指图中的节点类型和关系类型都仅有一种。那么这种图就不会存在节点分类。因为节点只有一种类型。

**Comment by FighterLYL** [comment]
> 作者您好，我感觉第五页K阶子图定义有些问题。这里面写的E‘={eij|任意 vj,d(vi,vj)<=k}
> 这里面如果eij图中根本不存在这条边，但是存在这个路径所以说这可能会有些问题。所以我认为E‘={elm|任意 vj,d(vi,vj)<=k，elm属于Pij}
> 希望得到您的回复。目前正在认真阅读图卷积知识。

你理解的对, 严格来说这个定义需要保证e_{ij}在边的集合中

**Comment by FighterLYL** [comment]
> 第8页，如果同构图是指图中的节点类型和关系类型都仅有一种。那么这种图就不会存在节点分类。因为节点只有一种类型。

这个地方你混淆了节点类型与标记, 比如说由论文引用关系构成的图中, 节点类型只有论文, 关系只有引用, 因此是一个同构图, 但可以进行论文领域分类的任务

**Comment by alice-cool** [comment]
谢谢(*°∀°)=3



---原始邮件---
发件人: "FighterLYL"<notifications@github.com&gt;
发送时间: 2021年1月15日(星期五) 下午5:14
收件人: "FighterLYL/GraphNeuralNetwork"<GraphNeuralNetwork@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Donglearner"<2524981200@qq.com&gt;;
主题: Re: [FighterLYL/GraphNeuralNetwork] 第五页K阶子图定义 (#49)




  
第8页，如果同构图是指图中的节点类型和关系类型都仅有一种。那么这种图就不会存在节点分类。因为节点只有一种类型。
  
这个地方你混淆了节点类型与标记, 比如说由论文引用关系构成的图中, 节点类型只有论文, 关系只有引用, 因此是一个同构图, 但可以进行论文领域分类的任务
