### ISSUE TITLE
第5章勘误

### ISSUE THREAD

**Issue by shenxiangzhuang** [FighterLYL/GraphNeuralNetwork#51]
2020年11月第一版第5次印刷。
1. P85， 公式(5.7)<img src="https://render.githubusercontent.com/render/math?math=Lx">结果应该为列向量，所以最后结果方括号外面应该加转置。
2. P86, 上面数第二三行：由式(5.7)可知：<img src="https://render.githubusercontent.com/render/math?math=LI =0">,因此……
这里是否有误？`I`表示单位矩阵的话，只能得到<img src="https://render.githubusercontent.com/render/math?math=LI =L">才对。

我的理解是：当图信号的强度全部相同的时候，我们得到<img src="https://render.githubusercontent.com/render/math?math=Lx =\lambda x = \mathbf{0}">, 所以<img src="https://render.githubusercontent.com/render/math?math=\lambda =0">, 即Laplacian Matrix可能的最小的特征值为0.

**Comment by FighterLYL** [comment]
这里的`I`本意是指全1向量, 而不是单位向量, 这个符号有些误导人.

**Comment by shenxiangzhuang** [comment]
> 这里的`I`本意是指全1向量, 而不是单位向量, 这个符号有些误导人.
ok.可以参考下这个https://mathoverflow.net/questions/9898/notation-for-the-all-ones-vector
