### ISSUE TITLE
公式5.18如何理解

### ISSUE THREAD

**Issue by jiaminglei-lei** [FighterLYL/GraphNeuralNetwork#53]
公式5.18，为什么y=Hx能够变成右边的形式？h(λ_k)是什么含义？

**Comment by FighterLYL** [comment]
y=Hx能够变成右边的依据是图滤波器的定义：
```
图滤波器：对给定图信号的频谱中各个频率分量的强度进行增强或者衰减的操作
```
h(λ_k) 是一个与频率相关的函数，相当于每个频率的权重系数，也就是起到对频率进行增强或者衰减的作用
